### ISSUE TITLE
Incompatible with typescript V5

### ISSUE THREAD

**Issue by paulrostorp** [kolking/react-native-userpic#1]
@kolking After upgrading to ts@5, I get the following issue from `Badge.tsx`:

![Screenshot 2023-06-01 at 10 25 34](https://github.com/kolking/react-native-userpic/assets/1866649/21d0fcee-920c-4c75-8375-77434ec2e609)

I think the statement should be:
```js
const displayValue = typeof value === 'number' && typeof limit == "number" && value > limit ? `${limit}+` : value;
```

**Comment by kolking** [comment]
Thanks! I'll push a quick PR with the fix.

**Comment by kolking** [comment]
The latest version `1.0.1` contains this fix.
