### ISSUE TITLE
Add a way to disable logs

### ISSUE THREAD

**Issue by andreirat** [kolking/react-native-userpic#24]
Currently, in dev mode, there are some logs for each render of the component. 

```RENDER <Userpic> Username```

A prop or something to disable logs in dev mode would help. It's helpful sometimes, but most of the times, because of the large number of avatars in a screen, is hard to debug other things using the console.

**Comment by matsossah** [comment]
Same here, is there a way to disable the log in Userpic.tsx?

   // debug('RENDER <Userpic>', name || email || imageSource);

**Comment by Zarinia** [comment]
> Same here, is there a way to disable the debug log in Userpic.tsx?
> 
> // debug('RENDER ', name || email || imageSource);

You can create patch file with this command
``` npx patch-package react-native-userpic ```
Result:

```
diff --git a/node_modules/react-native-userpic/src/Userpic.tsx b/node_modules/react-native-userpic/src/Userpic.tsx
index 15390cc..690e7f1 100644
--- a/node_modules/react-native-userpic/src/Userpic.tsx
+++ b/node_modules/react-native-userpic/src/Userpic.tsx
@@ -64,7 +64,7 @@ const Userpic = ({
     setImageSource(defaultSource);
   }, [defaultSource]);
 
-  debug('RENDER <Userpic>', name || email || imageSource);
+  // debug('RENDER <Userpic>', name || email || imageSource);
 
   return (
     <View {...props} style={[styles.root, { width: size, height: size }]}>

```

**Comment by kolking** [comment]
Please upgrade to `v2.1.0`
